### ISSUE TITLE
How  to run tinyDTLS in instantContiki2.7 ?

### ISSUE THREAD

**Issue by pengkunlunHIT** [cetic/tinydtls#2]
By using ./configure , make, ./tests/dtls-client ::1 ,I can run tinyDTLS in ordinary linux .

But when i extract the tinydtls-0.8.2.tar.gz  file to ~/contiki/apps/tinydtls-0.8.2,  and  use ./configure -with-contiki, and edit the /tinydtls-0.8.2/Makefile  by adding  APPS += tinydtls/aes tinydtls/sha2 tinydtls/ecc tinydtls,
when i make ,it turns out that : dlts-server.c error:tinydtls.h: No such file or directory

How to solve this problem? I am anxious and really look forward your help,thanks a lot.
The Makefile and the compile error picture are as follow
![instantcontiki2 7-2015-10-08-17-20-12](https://cloud.githubusercontent.com/assets/9984580/10362468/60c3f8c0-6de1-11e5-9427-eec5ac5c9917.png)
![instantcontiki2 7-2015-10-08-17-20-41](https://cloud.githubusercontent.com/assets/9984580/10362469/60ccfcae-6de1-11e5-9353-6fd9a5b324df.png)

**Comment by laurentderu** [comment]
This is not the official Github for TInyDTLS, only a local copy for integration for 6LBR.

Your error is trivial though, you must extract TinyDTLS into ~/contiki/apps/tinydtls, not ~/contiki/apps/tinydtls-0.8.2

**Comment by pengkunlunHIT** [comment]
Thank you very much,i exactly found this error by myself and have already renamed the file as tinydtls after i raised this question,but it still are some problems such as undefined reference to  uip_ds6_if in examples/contiki/dtls-server.c. The details are in the following picture.

could you please help me?And i really appreciate your help if you could please tell me the whole detailed steps to run tinydtls on instantContiki2.7. Thanks a lot.
![new issue](https://cloud.githubusercontent.com/assets/9984580/10396384/d6a3a63c-6ed4-11e5-85ff-9a3bf624d995.png)

**Comment by pengkunlunHIT** [comment]
When i specify the target as sky motes in Cooja, it turns out the error that dtls-server.sky section '.text' will not fit in region 'rom'  and contiki-sky-main.c relocation turncated to fit.
Detailed errors are in the following picture.
Any help will be sincerely appreciated.Thank you.
![10 10 issue](https://cloud.githubusercontent.com/assets/9984580/10411473/de14b7ce-6f99-11e5-9fd7-0c8a23130c5b.png)

**Comment by laurentderu** [comment]
I think the error message is quite clear, the Sky target is too small for your binary !

Either switch to Wismote, Coojamote or exp5438
