### ISSUE TITLE
Error While Making the Tinydtls

### ISSUE THREAD

**Issue by 14MCEN27** [cetic/tinydtls#3]
make -C examples/contiki all
make[1]: Entering directory `/home/user/Desktop/tinydtls-0.8.2/examples/contiki'
Makefile:62: ../../../../Makefile.include: No such file or directory
make[1]: *** No rule to make target`../../../../Makefile.include'.  Stop.
make[1]: Leaving directory `/home/user/Desktop/tinydtls-0.8.2/examples/contiki'
make: **\* [all] Error 2

**Comment by laurentderu** [comment]
This is not the official Github for TinyDTLS, only a local copy for integration for 6LBR.

**Comment by 14MCEN27** [comment]
can you please mail me original copy?

On Thu, Feb 25, 2016 at 10:30 PM, Laurent Deru notifications@github.com
wrote:

> This is not the official Github for TinyDTLS, only a local copy for
> integration for 6LBR.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cetic/tinydtls/issues/3#issuecomment-188878490.

## 

Foram Suthar
TA   CSE(NT)  Dept,
Institute of Technology,
Nirma University,  Ahmedabad
